#' ACF Test Explanation
#'
#' Generates text on why the sample autocorrelation of the residuals from a time series model 
#' fails the Ljung-Box or Box-Pierce Q test.
#'
#' Version 4.1, 2024-05-15
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param acf_lags_fail - lags of the ACF to test
#'        Default is \code{c(1, 2, 3, 4, 12, 24)}.
#' @param num_sig - limit for number of lags with significant ACF values
#'        Default is \code{8}.
#' @param include_pacf Logical scalar that indicates if the PACF is included in the testing.
#'        Default is TRUE
#' @param return_both Logical scalar indicating whether the calling function will return both the 
#'        test results and why the test failed or just produce a warning. Default is \code{FALSE}.
#' @return Character object that tells why series fails the ACF test, \code{'pass'} otherwise.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_acf_fail_why <- acf_fail_why(ukgas_udg, acf_lags_fail = c(1, 2, 3, 4, 8), 
#'                                    num_sig = 4, return_both = TRUE)
#' @export
acf_fail_why <- function(udg_list = NULL, acf_lags_fail = c(1, 2, 3, 4, 12, 24), 
                         num_sig = 8, include_pacf = TRUE, return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 4.1, 2024-05-15
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize \code{this_out_string}
    this_out_string <- ""
    
    # Extract the number of significant ACF lags for the Ljung Box Q
    n_q_sig <- udg_list[["nlbq"]]
    
    # If the number of significant ACF lags (Ljung-Box Q) is greater than \code{numsig}, set
    # \code{this_out_string} to show why the diagnostic failed
    if (n_q_sig >= num_sig) {
        this_out_string <- paste("nLBQsig > ", num_sig, sep = "")
        if (!return_both) {
            this_out_string <- paste("fail:", this_out_string, sep = " ")
        }
    }
    # Extract the number of significant ACF lags for the Box Pierce Q
    n_q_sig <- udg_list[["nbpq"]]
    
    # If the number of significant ACF lags (Box Pierce Q) is greater than \code{num_sig},
    # set \code{this_out_string} to show why the diagnostic failed
    if (n_q_sig >= num_sig) {
        if (nchar(this_out_string) == 0) {
            this_out_string <- paste("nBPQsig > ", num_sig, sep = "")
            if (!return_both) {
                this_out_string <- paste("fail:", this_out_string, sep = " ")
            }
        } else {
            this_out_string <- paste(this_out_string, "; nBPQsig > ", num_sig, sep = "")
        }
    }
    
    # Extract the number of significant ACF lags
    n_q_sig <- udg_list[["nsigacf"]]
    # If the number of significant ACF lags if greater than 0, check to see if one of the 
    # values of \code{acf_lags_fail} is a significant lag; if so, set \code{this_out_string} 
    # to show why the diagnostic failed
    if (n_q_sig > 0) {
        for (i in 1:length(acf_lags_fail)) {
            this_lag <- sum(udg_list[["sigacflags"]] == acf_lags_fail[i])
            if (this_lag > 0) {
                if (nchar(this_out_string) == 0) {
                  this_out_string <- paste("sigacf(", acf_lags_fail[i], ")", sep = "")
                  if (!return_both) {
                    this_out_string <- paste("fail:", this_out_string, sep = " ")
                  }
                } else {
                  this_out_string <- paste(this_out_string, "; sigacf(", acf_lags_fail[i], ")", sep = "")
                }
            }
        }
    }
    
    if (include_pacf) {
        # Extract the number of significant PACF lags
        n_q_sig <- udg_list[["nsigpacf"]]
    
        # If the number of significant PACF lags if greater than 0, check to see if one of the values of
        # \code{acf_lags_fail} is a significant lag - add text describing error to \code{this_out_string}
        if (n_q_sig > 0) {
            for (i in 1:length(acf_lags_fail)) {
                this_lag <- sum(udg_list[["sigpacflags"]] == acf_lags_fail[i])
                if (this_lag > 0) {
                    if (nchar(this_out_string) == 0) {
                        this_out_string <- paste("sigpacf(", acf_lags_fail[i], ")", sep = "")
                        if (!return_both) {
                            this_out_string <- paste("fail:", this_out_string, sep = " ")
                        }
                    } else {
                        this_out_string <- paste(this_out_string, "; sigpacf(", acf_lags_fail[i], ")", sep = "")
                    }
                }
            }
        }
    }
    
    # if \code{this_out_string} has length 0, return pass, else return \code{this_out_string}
    if (nchar(this_out_string) == 0) {
        if (return_both) {
            return("    ")
        } else {
            return("pass")
        }
    } else {
        return(this_out_string)
    }
}
