#' ACF test warning message
#'
#' Tests whether the residuals from a time series model generates a warning for the ACF test.
#'
#' Version 2.6, 05/15/2024
#'
#' @param udg_list - list object generated by \code{udg()} function of the \code{seasonal} package.
#         This is a required entry.
#' @param acf_lags_warn - lags of the ACF to test for warnings
#' @return Logical object which is \code{TRUE} if series generates a warning for the ACF test, 
#'         \code{FALSE} otherwise.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)",
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_acf_warn <- acf_warn(ukgas_udg, acf_lags_warn = c(4,8))
#' @export
acf_warn <- function(udg_list = NULL, acf_lags_warn = c(12, 24)) {
    # Author: Brian C. Monsell (OEUS) Version 2.6, 05/15/2024
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize \code{this_warn} to \code{FALSE}
    this_warn <- FALSE
    
    # Extract the number of significant ACF lags for the Ljung Box Q
    n_q_sig <- udg_list[["nlbq"]]
    
    # if number of significant lags is greater than 0, loop though \code{acf_lags_warn} and see if
    # any of them are listed as significant
    if (n_q_sig > 0) {
        for (i in 1:length(acf_lags_warn)) {
            this_lag <- sum(udg_list[["lblags"]] == acf_lags_warn[i])
            if (this_lag > 0) {
                this_warn <- TRUE
            }
        }
    }
    # If \code{this_warn} \code{TRUE}, return \code{this_warn}
    if (this_warn) {
        return(this_warn)
    }
    
    # Extract the number of significant ACF lags for the Box Pierce Q.  If none of them are
    # significant, return \code{this_warn}
    n_q_sig <- udg_list[["nbpq"]]
    if (n_q_sig == 0) {
        return(this_warn)
    }
    
    # if number of significant lags is greater than 0, loop though \code{acf_lags_warn} and check if
    # any of them are listed as significant
    for (i in 1:length(acf_lags_warn)) {
        this_lag <- sum(udg_list[["bplags"]] == acf_lags_warn[i])
        if (this_lag > 0) {
            this_warn <- TRUE
        }
    }
    
    # return \code{this_warn}
    return(this_warn)
    
}
