#' ACF Test Warning Message
#'
#' Generates text on why the sample autocorrelation of the residuals from a time series model fails the Ljung-Box or Box-Pierce Q test
#'
#' Version 3.5, 5/25/2023
#'
#' @param udg_list - list object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param acf_lags_warn - lags of the ACF to test for warnings
#'        Default is \code{c(12, 24)}.
#' @param return_both Logical scalar indicating whether the calling function will return both the test results and why the test failed or produced a warning. Default is FALSE.
#' @return Character string which tells why the series generates a warning for the ACF test, 'pass' otherwise.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)",
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_acf_warn_why <- acf_warn_why(ukgas_udg, acf_lags_warn = c(4, 8), return_both = TRUE)
#' @export
acf_warn_why <- function(udg_list = NULL, acf_lags_warn = c(12, 24), return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 3.5, 5/25/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize this_out_string
    this_out_string <- ""
    
    # Extract the number of significant ACF lags for the Ljung Box Q
    n_q_sig <- udg_list[["nlbq"]]
    
    # if number of significant lags is greater than 0, loop though \code{acf_lags_warn} and see if
    # any of them are listed as significant.  If significant lags are found, generate warning message
    # in \code{this_out_string}
    all_lags <- 0
    if (n_q_sig > 0) {
        for (i in 1:length(acf_lags_warn)) {
            this_lag <- sum(udg_list[["lblags"]] == acf_lags_warn[i])
            if (this_lag > 0) {
                if (all_lags == 0) {
                  this_out_string <- paste("lbq(", acf_lags_warn[i], ")", sep = "")
                  if (!return_both) {
                    this_out_string <- paste("warn:", this_out_string, sep = " ")
                  }
                } else {
                  this_out_string <- paste(this_out_string, "; lbq(", acf_lags_warn[i], ")", sep = "")
                }
                all_lags <- all_lags + this_lag
            }
        }
    }
    
    # Extract the number of significant ACF lags for the Box Pierce Q.  If none of them are
    # significant, return \code{this_out_string}.
    n_q_sig <- udg_list[["nbpq"]]
    if (n_q_sig == 0) {
        return(this_out_string)
    }
    
    # if number of significant lags is greater than 0, loop though \code{acf_lags_warn} and see if
    # any of them are listed as significant.  If significant lags are found, generate warning message
    # in \code{this_out_string}
    for (i in 1:length(acf_lags_warn)) {
        this_lag <- sum(udg_list[["bplags"]] == acf_lags_warn[i])
        if (this_lag > 0) {
            if (all_lags == 0) {
                this_out_string <- paste("bpq(", acf_lags_warn[i], ")", sep = "")
                if (!return_both) {
                  this_out_string <- paste("warn:", this_out_string, sep = " ")
                }
            } else {
                this_out_string <- paste(this_out_string, "; bpq(", acf_lags_warn[i], ")", sep = "")
            }
            all_lags <- all_lags + this_lag
        }
    }
    
    # If all_lags > 0, return \code{this_out_string}
    if (all_lags > 0) {
        return(this_out_string)
    } else {
        if (return_both) {
            return("    ")
        } else {
            return("pass")
        }
    }
    
}
