#' ACF Test failure message
#'
#' Tests whether the sample autocorrelation of the residuals from a time series model fails 
#' the Ljung-Box or Box-Pierce Q test.
#'
#' Version 3.2, 2024-05-15
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param acf_lags_fail Lags of the ACF to test
#'        Default is \code{c(1, 2, 3, 4, 8)}.
#' @param num_sig Limit for number of lags with significant ACF values
#'        Default is \code{4}.
#' @param include_pacf Logical scalar that indicates if the PACF is included in the testing.
#'        Default is TRUE
#' @return Logical object which is \code{TRUE} if series fails the ACF test, \code{FALSE} otherwise
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)",
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_acf_fail <- acf_fail(ukgas_udg, acf_lags_fail = c(1, 2, 3, 4, 8), num_sig = 4)
#' @export
acf_fail <- function(udg_list = NULL, acf_lags_fail = c(1, 2, 3, 4, 12, 24), num_sig = 8,
                     include_pacf = TRUE) {
    # Author: Brian C. Monsell (OEUS) Version 3.2, 2024-05-15
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize \code{this_fail} to \code{FALSE}
    this_fail <- FALSE
    
    # Extract the number of significant ACF lags for the Ljung Box Q
    n_q_sig <- udg_list[["nlbq"]]
    
    # If the number of significant ACF lags (Ljung-Box Q) is greater than \code{num_sig}, set
    # \code{this_fail} to \code{TRUE} and return \code{this_fail}
    if (n_q_sig >= num_sig) {
        this_fail <- TRUE
        return(this_fail)
    }
    
    # Extract the number of significant ACF lags for the Box Pierce Q
    n_q_sig <- udg_list[["nbpq"]]
    
    # If the number of significant ACF lags (Box Pierce Q) is greater than \code{num_sig}, set
    # \code{this_fail} to \code{TRUE} and return \code{this_fail}
    if (n_q_sig >= num_sig) {
        this_fail <- TRUE
        return(this_fail)
    }
    
    # Extract the number of significant ACF lags
    n_q_sig <- udg_list[["nsigacf"]]
    
    # If the number of significant ACF lags if greater than 0, check to see if one of the values of
    # \code{acf_lags_fail} is a significant lag - set \code{this_fail} to \code{TRUE} and return
    if (n_q_sig > 0) {
        for (i in 1:length(acf_lags_fail)) {
            this_lag <- sum(udg_list[["sigacflags"]] == acf_lags_fail[i])
            if (this_lag > 0) {
                this_fail <- TRUE
                return(this_fail)
            }
        }
    }
    
    if (include_pacf) {
        # Extract the number of significant PACF lags
        n_q_sig <- udg_list[["nsigpacf"]]
    
        # If the number of significant PACF lags if greater than 0, check to see if one of the values of
        # \code{acf_lags_fail} is a significant lag - set \code{this_fail} to \code{TRUE} and return
        if (n_q_sig > 0) {
            for (i in 1:length(acf_lags_fail)) {
                this_lag <- sum(udg_list[["sigpacflags"]] == acf_lags_fail[i])
                if (this_lag > 0) {
                    this_fail <- TRUE
                    return(this_fail)
                }
            }
        }
    }
    
    return(this_fail)
}
