#' Combined spectrum test from Maravall (2012)
#'
#' Generate a test for seasonality by combining the results from the AR(30) and Tukey nonparametric
#' spectrums as laid out in Maravall (2012)
#'
#' Version 2.7, 5/14/2024
#'
#' @param seas_obj \code{seas} object for a single series. This is a required entry.
#' @param this_ar_spec_cv List object with two elements - 99 and 95 percent critical values for 
#'        the frequencies of the AR(30) spectrum as generated by the \code{gen_ar_spec_cv} 
#         function. This is a required entry.
#' @param this_series character string; the table used to generate the AR(30) spectrum. 
#'        Default is \code{"b1"}.
#' @param take_log logical scalar; indicates if the AR spectrum is generated from the log of 
#'        the data. Default is \code{TRUE}.
#' @param take_diff logical scalar; indicates if the data is differenced before the AR spectrum 
#'        is generated. Default is \code{TRUE}.
#' @return \code{TRUE} if spectral evidence of seasonality is detected; \code{FALSE} if not.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' air_seas <- seasonal::seas(AirPassengers, series.save = "b1",
#'                     arima.model="(0 1 1)(0 1 1)",
#'                     forecast.maxlead = 36, slidingspans = "",
#'                     transform.function = "log")
#' this_ar30_spec_cv <- gen_ar_spec_cv(1000, 97, 12)
#' this_spectrum_test <- combined_spectrum_test(air_seas, this_ar30_spec_cv)
#' @export
combined_spectrum_test <- function(seas_obj = NULL, this_ar_spec_cv = NULL, 
                                   this_series = "series.adjoriginal",
                                   take_log = TRUE, take_diff = TRUE) {
   # Author: Brian C. Monsell (OEUS) Version 2.7, 5/14/2024
    
   # check if a value is specified for \code{seas_obj}
   if (is.null(seas_obj)) {
       stop("must specify a seas object")
   } else {
        if (!inherits(seas_obj, "seas")) {
           stop("First argument must be a seas object")
       }
   }
    
   # check if a value is specified for \code{this_ar_spec_cv}
   if (is.null(this_ar_spec_cv)) {
       stop("must specify a value for the this_ar_spec_cv argument")
   }

   this_freq <- as.numeric(sautilities::get_udg_entry(seas_obj, "freq"))

   this_start_spec_string <- seasonal::udg(seas_obj, "startspec")
   this_start_spec        <- convert_date_string_to_date(this_start_spec_string)

   this_x <- window(seasonal::series(seas_obj, this_series), start = this_start_spec)
   if (take_log) {
       this_x <- log(this_x)
   }
   if (take_diff) {
       this_x <- diff(this_x)
   }

   this_ar_spec <- spec.ar(this_x, 61, 30, plot = FALSE)

   if (this_freq == 12) {
       f_index <- c(11, 21, 31, 41, 51, 61)
       f_num   <- 6
   } else {
       f_index <- c(31, 61)
       f_num   <- 2
   }

   median_spec <- median(this_ar_spec$spec)
   range_spec  <- diff(range(this_ar_spec$spec))

   this_rw <- array(0, dim = f_num)
   for (j in 1:(f_num - 1)) {
       j_index <- f_index[j]
       if (this_ar_spec$spec[j_index] > median_spec) {
           this_rw[j] <-
                 min(this_ar_spec$spec[j_index] - this_ar_spec$spec[j_index-1],
                     this_ar_spec$spec[j_index] - this_ar_spec$spec[j_index+1]) / range_spec
      }
   }

   j_index <- f_index[f_num]
   if (this_ar_spec$spec[j_index] > median_spec) {
       this_rw[f_num] <-
             (this_ar_spec$spec[j_index] - this_ar_spec$spec[j_index-1]) / range_spec
   }

   ar_spec_strong_peak <- array(FALSE, dim = f_num)
   ar_spec_weak_peak <- array(FALSE, dim = f_num)
   for (i in 1:f_num) {
       ar_spec_strong_peak[i] <- this_rw[i] > this_ar_spec_cv$cv99[i]
       if (!ar_spec_strong_peak[i]) {
           ar_spec_weak_peak[i] <- this_rw[i] > this_ar_spec_cv$cv95[i]
       }
   }

   if (this_freq == 12) {
      this_tukey_spec <-
         c(as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s1")),
           as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s2")),
           as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s3")),
           as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s4")),
           as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s5")),
           as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s6")))
   } else {
      this_tukey_spec <-
           c(as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s1")),
             as.numeric(sautilities::get_udg_entry(seas_obj, "spcori.tukey.s2")))
   }

   tukey_spec_strong_peak <- array(FALSE, dim = f_num)
   tukey_spec_weak_peak <- array(FALSE, dim = f_num)
   for (i in 1:f_num) {
       tukey_spec_strong_peak[i] <- this_tukey_spec[i] > 0.99
       if (!tukey_spec_strong_peak[i]) {
           tukey_spec_weak_peak[i] <- this_tukey_spec[i] > 0.95
       }
   }

   combined_strong_peak <- ar_spec_strong_peak & tukey_spec_strong_peak
   combined_weak_peak   <- ar_spec_weak_peak   | tukey_spec_weak_peak

   if (this_freq == 12) {
       strongpeak1 <- sum(combined_strong_peak[1:5])
       weakpeak1   <- sum(combined_weak_peak[1:5])
       if ((strongpeak1 + weakpeak1) >= 2 && strongpeak1 > 0) {
           return(TRUE)
       }

       if (combined_strong_peak[6] && strongpeak1 > 0) {
           return(TRUE)
       }

       if (sum(combined_weak_peak) > 3) {
           return(TRUE)
       }

       if (combined_strong_peak[6] && weakpeak1 > 1) {
           return(TRUE)
       }
   } else {
       if (this_freq == 4) {
           if (combined_strong_peak[1]) {
               return(TRUE)
           }

           if (sum(combined_weak_peak) == 2) {
               return(TRUE)
           } else {
              if (combined_strong_peak[2] && combined_weak_peak[1]) {
                   return(TRUE)
              }
           }
       }
   }

   return(FALSE)

}
