#' ACF Test Warning Message
#'
#' Shows why D11 f-test for residual seasonality fails.
#'
#' Version 4.2, 5/24/2023
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param p_level p-level used to test the d11 f-test for residual seasonality
#'        Default is \code{0.01}.
#' @param return_both Logical scalar indicating whether the calling function will return both 
#'        the test results and why the test failed or produced a warning. Default is \code{FALSE}.
#' @return A text string denoting why a series fails or has a warning for residual seasonality. 
#'         If d11f statistic not found, return \code{'none'}.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- 
#'    seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                   x11="", transform.function = "log", forecast.maxlead=20,
#'                   check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_d11f_why <- d11f_test_why(ukgas_udg, p_level = 0.05, return_both = TRUE)
#' @export
d11f_test_why <- function(udg_list = NULL, p_level = 0.01, return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 4.2, 5/24/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize \code{this_test}
    this_test <- "    "
    
    # Check to see if d11.f is one of the diagnostics in the UDG file
    this_index <- get_udg_index(udg_list, "d11.f")
    
    # If not in the file, return 'none'
    if (this_index == 0) {
        return("none")
    }
    # Extract p-value for D11 F-statistic
    this_p_value <- udg_list[["d11.f"]][2]/100
    
    # If p-value is less than limit set, store a warning message into \code{this_test}
    if (this_p_value < p_level) {
        this_test <- paste("p_level(d11.f) < ", p_level, sep = "")
        if (!return_both) {
            this_test <- paste("warn: ", this_test, sep = "")
        }
    } else {
        # Extract p-value for D11 F-statistic for last 3 years of data
        this_3y_p_level <- udg_list[["d11.3y.f"]][2]/100
        
        # If p-value is less than limit set, store a warning message into \code{this_test}
        if (this_3y_p_level < p_level) {
            this_test <- paste("p_level(d11f_3y) < ", p_level, sep = "")
            if (!return_both) {
                this_test <- paste("warn: ", this_test, sep = "")
            }
            # else, set \code{this_test} to 'pass'
        } else {
            if (!return_both) {
                this_test <- "pass"
            }
        }
    }
    
    # return \code{this_test}
    return(this_test)
}
