#' Get entry from UDG file
#'
#' Returns a specific element of a list of \code{udg} entries.
#'
#' Version 2.7 5/14/2024
#'
#' @param seas_obj \code{seas} object for a single series
#' @param this_key character scalar; keyword found in UDG output generated by \code{X-13ARIMA-SEATS}.
#' @param this_index integer scalar; index of entry in vector to extract. If set to 0 (the default), 
#'        get the last entry.
#' @param convert logical scalar; if \code{TRUE}, convert character to numeric object.
#'        Default is \code{TRUE}.
#' @return The \code{this_index} element of the array returned from the UDG entry for \code{this_key} 
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples 
#' air_seas_short <- seasonal::seas(AirPassengers, series.span = ',1960.9', 
#'                     arima.model="(0 1 1)(0 1 1)", 
#'                     forecast.maxlead = 36, slidingspans = "", 
#'                     transform.function = "log")
#' fcst_tstat <- get_udg_entry(air_seas_short, 'forctval01')
#' @export
get_udg_entry <- function(seas_obj = NULL, this_key, this_index = 0, convert = TRUE) {
    # Author: Brian C. Monsell (OEUS) Version 2.7 5/14/2024
    
    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        stop("must specify a seas object")
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
           stop("First argument must be a seas object")
        }
    }

    # extract output associated with UDG keyword if UDG keyword not found, 
    # print out error message and set \code{this_udg_string} to \code{NULL}.
    this_udg_string <- tryCatch(seasonal::udg(seas_obj, this_key), error = function(e) {
        print(paste("this keyword not found: ", this_key, sep = ""))
        NULL
    })
    
    # if \code{this_udg_string} is \code{NULL}, return \code{NULL}
    if (is.null(this_udg_string)) {
        return(this_udg_string)
    }
    
    # if \code{this_udg_string} is fully numeric, return proper element in \code{this_udg_string}
    if (is.numeric(this_udg_string)) {
        # If \code{this_index} is not set by user, set to be the last element in the array
        if (this_index == 0) {
            this_index <- length(this_udg_string)
        }
        return(this_udg_string[this_index])
    }
    
    # if \code{this_udg_string} is an array, create a single string separated by spaces
    if (is.array(this_udg_string)) {
        this_udg_string <- paste(this_udg_string, collapse = " ")
    }
    
    # Recreate a character array by splitting the string by spaces
    this_vec <- unlist(strsplit(this_udg_string, split = " "))
    
    # If \code{this_index} is not set by user, set to be the last element in the array
    if (this_index == 0) {
        this_index <- length(this_vec)
    }
    
    # If \code{convert} is \code{TRUE}, return output as a number. 
    # If not, return as a character string
    if (convert) {
        return(as.numeric(this_vec[this_index]))
    } else {
        return(this_vec[this_index])
    }
}
