#' Probability of model based F-test
#'
#' Get probability for model based F-test, changing the model to remove seasonal differences 
#' and adding seasonal regressors if necessary. This function is used in the overall seasonal 
#' test from Maravall (2012)
#'
#' Version 4.4, 6/21/2024
#'
#' @param seas_obj \code{seas} object for a single series.
#'        This is a required entry.
#' @param this_series character string; the table used to generate the model based F-test. 
#'        Default is \code{"b1"}.
#' @param use_seasonal logical scalar; if TRUE, the \code{seasonal} regressor is used;
#'        otherwise, use the sine-cosine trignonmetric regressors generated by \code{sincos}.
#' @return test probability generated for the model based seasonal F-test used in the 
#'         seasonal testing procedure in Maravall(2012)
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples 
#' air_seas_seasonal <- 
#'   seasonal::seas(AirPassengers, arima.model="(0 1 1)",
#'                  regression.variables = "seasonal",
#'                  forecast.maxlead = 36, slidingspans = "", 
#'                  transform.function = "log", series.save = "a1")
#' air_ftest_prob <- sautilities::get_seasonal_ftest_prob(air_seas_seasonal)
#' @export
get_seasonal_ftest_prob <- function(seas_obj = NULL, this_series = "b1", use_seasonal = TRUE) {
    # Author: Brian C. Monsell (OEUS) Version 4.4, 6/21/2024

    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        stop("must specify a seas object")
    } else {
        if (!inherits(seas_obj, "seas")) {
           stop("First argument must be a seas object")
        }
    }
	
    if (use_seasonal) {
        this_key <- "ftest$Seasonal"
    } else {
        this_key <- "ftest$Trigonometric Seasonal"
    }

    this_udg <- seasonal::udg(seas_obj)
    this_index <- sautilities::get_udg_index(seasonal::udg(seas_obj), this_key)

    if (this_index > 0) {
        seasonal_ftest_prob <- 
            1.0 - sautilities::get_udg_entry(seas_obj, this_key)
    } else {
        seasonal_diff <- 
            as.numeric(sautilities::get_udg_entry(seas_obj,"seasonaldiff"))
        this_model <- this_udg$arimamdl
        if (seasonal_diff > 0) {
            this_new_model          <- paste0(substr(this_model,1,9), " 0 0)")
        } else {
            this_new_model          <- this_model
        }
		if (use_seasonal) {
			this_new_reg <- c(seas_obj$model$regression$variables, "seasonal")
		} else {
			this_new_reg <- c(seas_obj$model$regression$variables, "sincos[1,2,3,4,5,6]")
		}
        seas_obj_static <- seasonal::static(seas_obj, evaluate = TRUE)
        seas_obj_static_update <- 
            update(seas_obj_static, x = seasonal::series(seas_obj, this_series),
                   regression.variables = this_new_reg, 
                   arima.model = this_new_model)
        seasonal_ftest_prob <- 
            1.0 - sautilities::get_udg_entry(seas_obj_static_update, this_key)
    }
    
    return(seasonal_ftest_prob)
}