#' Model Test Warning Message
#'
#' Generates text on why a time series model is inadequate.
#'
#' Version 4.2, 5/23/2023
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param t_value Numeric scalar; t-statistic limit for regressors. Default is \code{3.0}
#' @param p_value Numeric scalar; p-value limit for regressors. Default is \code{0.01}
#' @param otl_auto_limit Integer scalar; limit for number of automatically identified outliers.
#'        Default is \code{4}
#' @param otl_all_limit Integer scalar; limit for number of automatically identified outliers.
#'        Default is \code{4}
#' @param return_both Logical scalar indicating whether the calling function will return 
#'        both the test results and why the test failed or produced a warning. 
#'        Default is \code{TRUE}.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @return A text string denoting why the series passed or failed a series of tests of 
#'         ARIMA diagnostics.
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_model_why <- 
#'      model_test_why(ukgas_udg, t_value=3.0, p_value=0.01, otl_auto_limit=4, 
#'                     otl_all_limit=6, return_both = TRUE)
#' @import stats
#' @export
model_test_why <- function(udg_list = NULL, t_value = 3, p_value = 0.05, otl_auto_limit = 5, 
    otl_all_limit = 5, return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 4.2, 5/23/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # check to see if model is fit
    if (udg_list[["mdg"]] == "no") {
        return("no model")
    }

    # check to see if the estimation of the regARIMA model converged in this run.  
    # if not, return \code{'no.convergance'}
    if (udg_list[["converged"]] == "no") {
        return("no convergance")
    }

    # check to see if either the total number of outliers or or the number of automatically identified
    # outliers are greater than their assigned limits in this run.  
    # if so, add \code{'number of outliers'} text to \code{this_out_string}
    this_out_string <- ""
    if (udg_list[["outlier.total"]] > otl_all_limit) {
        this_out_string <- paste0("number of outliers > ", otl_all_limit)
        if (!return_both) {
            this_out_string <- paste0("warn: ", this_out_string)
        }
    }
    if (sum(names(udg_list) == "autoout") > 0) {
        if (udg_list[["autoout"]] > otl_auto_limit) {
            if (nchar(this_out_string) > 0) {
                this_out_string <- paste0(this_out_string, ";")
            } else {
                if (!return_both) {
                  this_out_string <- "warn: "
                }
            }
            this_out_string <- paste0(this_out_string, " number of auto outliers > ", otl_auto_limit)
        }
    }
    
    # check to see if the regARIMA residuals pass Geary's a test for normality.  
    # if not, add \code{'residuals not normal'} to \code{this_out_string}
    this_index <- get_udg_index(udg_list, "a")
    if (this_index > 0) {
        this_geary_a <- udg_list[[this_index]]
        if (length(this_geary_a) == 2) {
            if (nchar(this_out_string) > 0) {
                this_out_string <- paste0(this_out_string, ";")
            } else {
                if (!return_both) {
                  this_out_string <- "warn: "
                }
            }
            this_out_string <- paste0(this_out_string, " residuals not normal")
        }
    }
    # check to see if at least one of the regression t-statistics is greater than tval, 
    # or the p-value is greater than pval.  if not, add text to \code{this_out_string}
    number_of_regs <- udg_list[["nreg"]]
    number_of_eff_obs <- udg_list[["nefobs"]]
    p_limit <- qt(1 - (p_value/2), df = number_of_eff_obs)
    if (number_of_regs > 0) {
        num_sig_t_value <- 0
        num_sig_p_value <- 0
        index_reg <- get_udg_index(udg_list, "nreg")
        for (i in 1:number_of_regs) {
            this_index <- index_reg + i
            this_t_stat <- udg_list[[this_index]][3]
            if (abs(this_t_stat) > t_value) {
                num_sig_t_value = num_sig_t_value + 1
            }
            if (abs(this_t_stat) > p_limit) {
                num_sig_p_value = num_sig_p_value + 1
            }
        }
        index_reg_derived <- get_udg_index(udg_list, "nregdev")
        if (index_reg_derived == 0) {
            if (num_sig_p_value == 0) {
                if (nchar(this_out_string) > 0) {
                  paste(this_out_string, ";", sep = "")
                } else {
                  if (!return_both) {
                    this_out_string <- "warn: "
                  }
                }
                this_out_string <- paste(this_out_string, "no P-values < ", p_value)
            }
            if (num_sig_t_value == 0) {
                if (nchar(this_out_string) > 0) {
                  this_out_string <- paste(this_out_string, ";", sep = "")
                } else {
                  if (!return_both) {
                    this_out_string <- "warn: "
                  }
                }
                this_out_string <- paste(this_out_string, "no t-values > ", t_value)
            }
        } else {
            for (i in 1:number_of_regs) {
                this_index <- index_reg_derived + i
                this_t_stat <- udg_list[[this_index]][3]
                if (abs(this_t_stat) > t_value) {
                    num_sig_t_value = num_sig_t_value + 1
                }
                if (abs(this_t_stat) > p_limit) {
                    num_sig_p_value = num_sig_p_value + 1
                }
            }
            if (num_sig_p_value == 0) {
                if (nchar(this_out_string) > 0) {
                  paste(this_out_string, ";", sep = "")
                } else {
                  if (!return_both) {
                    this_out_string <- "warn: "
                  }
                }
                this_out_string <- paste0(this_out_string, " no P-values < ", p_limit)
            }
            if (num_sig_t_value == 0) {
                if (nchar(this_out_string) > 0) {
                  this_out_string <- paste0(this_out_string, ";")
                } else {
                  if (!return_both) {
                    this_out_string <- "warn: "
                  }
                }
                this_out_string <- paste0(this_out_string, " no t-values > ", t_value)
            }
        }
    }
    
    # if text has been added to \code{this_out_string}, return the string 
    # else, return \code{'pass'}
    if (nchar(this_out_string) > 0) {
        return(this_out_string)
    } else {
        if (return_both) {
            return("    ")
        } else {
            return("pass")
        }
    }
}
