#' Normality Test Warning Message
#'
#' Generates message for why different normality statistics available in \code{X-13ARIMA-SEATS} fail.
#'
#' Version 3.2, October 2, 2020
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param this_norm Character scalar inidicating type of normality statistic being extracted; 
#'        permissable values are \code{'a'}, \code{'kurtosis'}, \code{'skewness'}.
#'        This is a required entry.
#' @param return_both Logical scalar indicating whether the calling function will return 
#'        both the test results and why the test failed or produced a warning. 
#'        Default is \code{FALSE}.
#' @return A text string showing why a series failed the specific normality test
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_norm_a_why <- norm_test_why(ukgas_udg, 'a', return_both = TRUE)
#' ukgas_norm_kurtosis_why <- norm_test_why(ukgas_udg, 'kurtosis', return_both = TRUE)
#' ukgas_norm_skewness_why <- norm_test_why(ukgas_udg, 'skewness', return_both = TRUE)
#' @export
norm_test_why <- function(udg_list = NULL, this_norm = NULL, return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 3.2, October 2, 2020
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # check if a value is specified for \code{this_norm}
    if (is.null(this_norm)) {
        stop("must specify a normality statistic (a, kurtosis, or skewness)")
    }
    
    # check \code{this_norm) after converting text to lower case
    this_norm <- tolower(this_norm)
    if (this_norm == "a" | this_norm == "kurtosis" | this_norm == "skewness") {
        this_norm_value <- udg_list[[this_norm]]
        if (is.null(this_norm_value)) {
            warning(paste(this_norm, " not found in this run"))
            return(NULL)
        }
        
        # extract normality statistic
        if (length(this_norm_value) > 1) {
            if (this_norm == "skewness") {
                # if skewness fails, return with proper error text
                if (this_norm_value[2] == "-") {
                  if (return_both) {
                    return("significant negative skewness")
                  } else {
                    return("fail: significant negative skewness")
                  }
                }
                if (this_norm_value[2] == "+") {
                  if (return_both) {
                    return("significant positive skewness")
                  } else {
                    return("fail: significant positive skewness")
                  }
                }
            }
            if (this_norm == "a") {
                # if a fails, return with proper error text
                if (return_both) {
                  return("Geary a significant at one percent level")
                } else {
                  return("fail: Geary a significant at one percent level")
                }
            }
            if (this_norm == "kurtosis") {
                # if kurtosis fails, return with proper error text
                if (return_both) {
                  return("Kurtosis significant at one percent level")
                } else {
                  return("fail: Kurtosis significant at one percent level")
                }
            }
        }
        return("pass")
    }
    
    warning(paste("fail: improper value of this_norm: ", this_norm))
    return(NULL)
    
}
