#' Normality Tests for Time Series Models.
#'
#' Tests different normality statistics available in X-13ARIMA-SEATS.
#'
#' Version 4.4, 5/14/2024
#'
#' @param seas_obj Object generated by \code{seas()} of the \code{seasonal} package.
#'        This is a required entry.
#' @param this_norm Type of normality statistic being extracted; 
#'        permissable values are \code{'a'}, \code{'kurtosis'}, \code{'skewness'}.
#'        This is a required entry.
#' @param return_this Character string; what the function returns - 
#'        \code{'test'} returns test results, \code{'why'} returns why the test failed or 
#'        received a warning, or \code{'both'}. Default is \code{'test'}.
#' @return  A text string denoting whether the series passed or failed the specific normality test. 
#'          If improper value is specified for this_norm, return \code{NULL}. 
#'          If no statistic is found, return \code{NA}.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- 
#'    seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                   x11 = "", transform.function = "log", forecast.maxlead = 20,
#'                   check.print = c( "pacf", "pacfplot" ))
#' ukgas_norm_a <- norm_test(ukgas_seas, 'a')
#' ukgas_norm_kurtosis <- norm_test(ukgas_seas, 'kurtosis')
#' ukgas_norm_skewness <- norm_test(ukgas_seas, 'skewness')
#' @export
norm_test <- function(seas_obj = NULL, this_norm = NULL, return_this = "test") {
    # Author: Brian C. Monsell (OEUS) Version 4.4, 5/14/2024
    
    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        stop("must specify a seas object")
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
           stop("First argument must be a seas object")
        }
    }

    # check if a value is specified for \code{this_norm}
    if (is.null(this_norm)) {
        stop("must specify a normality statistic (a, kurtosis, or skewness)")
    }
    
    # set \code{is_test}, \code{is_why}, \code{is_both}
    is_test <- FALSE
    is_why <- FALSE
    is_both <- FALSE
    return_this <- tolower(return_this)
    if (return_this == "test") {
        is_test <- TRUE
    }
    if (return_this == "why") {
        is_why <- TRUE
    }
    if (return_this == "both") {
        is_test <- TRUE
        is_why <- TRUE
        is_both <- TRUE
    }
    
    # check for improper entry for \code{return_this}
    if (!is_test & !is_why) {
        print(paste("Improper entry for return_this : ", return_this, sep = ""))
        return(NULL)
    }
    
    # check \code{this_norm) after converting text to lower case
    this_norm <- tolower(this_norm)
    if (this_norm == "a" | this_norm == "kurtosis" | this_norm == "skewness") {
        this_norm_stat <- get_norm_stat(seas_obj, this_norm)
        if (is.null(this_norm_stat)) {
            if (is_both) {
                return(c(this_norm_stat, this_norm_stat))
            } else {
                return(this_norm_stat)
            }
        }
        if (is.na(this_norm_stat)) {
            if (is_both) {
                return(c(this_norm_stat, this_norm_stat))
            } else {
                return(this_norm_stat)
            }
        }
        
        this_udg_list <- seasonal::udg(seas_obj)
        if (length(unlist(this_udg_list[this_norm])) > 1) {
            this_test <- "fail"
            this_why <- norm_test_why(this_udg_list, this_norm, return_both = is_both)
        } else {
            this_test <- "pass"
            this_why <- "    "
            if (return_this == "why") 
                this_why <- "pass"
        }
        # return test results or why text according to \code{return_this} argument
        
        if (is_both) {
            return(cbind(this_test, this_why))
        }
        if (is_test) {
            return(this_test)
        }
        return(this_why)
    }
    
    warning(paste("improper value of this_norm: ", this_norm, sep = ""))
    return(NULL)
    
}
