#' Second overall sasonality test from Maravall (2012)
#'
#' Conduct the second overall test for seasonality as laid out in Maravall (2012)
#'
#' Version 4.1, 5/14/2024
#'
#' @param seas_obj \code{seas} object generated by the \code{seasonal} package.
#'        This is a required entry.
#' @param this_ar_spec_cv List object with two elements - 99 and 95 percent critical values for 
#'        the frequencies of the AR(30) spectrum as generated by the \code{gen_ar_spec_cv} 
#'        function.
#' @param this_series character string; the table used to generate the AR(30) spectrum. 
#'        Default is \code{"b1"}.
#' @param this_ori_qs character string; code for which original series QS will be used in this 
#'        analysis. Default is \code{"qssorievadj"} (original series adjusted for extreme values, 
#'        short span); other choices are \code{"qsori"} (original series, full span), 
#'        \code{"qsorievadj"} (original series adjusted for extreme values, full span), and 
#'        \code{"qssori"} (original series, short span)
#' @param take_log logical scalar; indicates if the AR spectrum is generated from the log of 
#'        the data. Default is \code{TRUE}.
#' @param take_diff logical scalar; indicates if the data is differenced before the AR spectrum is 
#'        generated. Default is \code{TRUE}.
#' @param use_seasonal logical scalar; if TRUE, the \code{seasonal} regressor is used;
#'        otherwise, use the sine-cosine trignonmetric regressors generated by \code{sincos}.
#' @return A list with 5 elements: \code{QStest} (test probability for QS), 
#'         \code{NPtest} (test probability for NP), 
#'         \code{Ftest} (test probability for model based seasonal F-test), 
#'         \code{spectrum} (character string with test result - possible values of either 
#'         \code{"evidence of seasonal peak"}, \code{"no evidence of seasonal peak"}),
#'         and \code{result} (character string with test result - possible values of either
#'         \code{"strong seasonal"}, \code{"weak seasonal"}, \code{"no seasonal"}.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' air_seas <- seasonal::seas(AirPassengers,
#'                     arima.model="(0 1 1)(0 1 1)",
#'                     series.save = "b1",
#'                     forecast.maxlead = 36, slidingspans = "",
#'                     transform.function = "log")
#' ar30_spec_cv <- gen_ar_spec_cv(1000, 97, 12)
#' second_test <- overall_seasonal_test_2(air_seas, ar30_spec_cv)
#' @export
overall_seasonal_test_2 <- 
    function(seas_obj = NULL, this_ar_spec_cv = NULL, this_series = "b1", this_ori_qs = "qssorievadj",
             take_log = TRUE, take_diff = TRUE, use_seasonal = TRUE) {
    # Author: Brian C. Monsell (OEUS) Version 4.1, 5/14/2024

    # check if a value is specified for \code{seas_obj}
    if (is.null(seas_obj)) {
        stop("must specify a seas object")
    } else {
    # check if a seas object is specified for \code{seas_obj}
        if (!inherits(seas_obj, "seas")) {
           stop("First argument must be a seas object")
        }
    }

    
    this_x <- seasonal::series(seas_obj, this_series)
    if (take_log) { this_x <- log(this_x) }

    this_NP     <- NP_test(this_x)
    this_QS     <- 1.0 - as.vector(seasonal::udg(seas_obj, this_ori_qs))[2]
    
    this_spectrum_test <- combined_spectrum_test(seas_obj, this_ar_spec_cv, this_series,
                                                 take_log, take_diff)
    if (this_spectrum_test) {
        this_spectrum_peak <- "evidence of seasonal peak"
    }
    else {
        this_spectrum_peak <- "no evidence of seasonal peak"
    }
    this_F      <- get_seasonal_ftest_prob(seas_obj, this_series, use_seasonal)

    this_result <- "no evidence"
    if ((this_QS > 0.99 & this_F > 0.95) | (this_QS > 0.95 & this_F > 0.99)) {
        this_result <- "strong evidence"
    } else {
        if (this_QS < 0.99 & this_F < 0.99) {
            this_result <- "no evidence"
        } else {
            if (this_QS > 0.99) {
                if ((this_F < 0.99) | (this_NP$cv < 0.99) | (!this_spectrum_test)) {
                    this_result <- "weak evidence"
                }
            }
            if (this_F > 0.99) {
                if ((this_QS < 0.99) | (this_NP$cv < 0.99) | (!this_spectrum_test)) {
                    this_result <- "weak evidence"
                }
            }
        }
    }

    return(list(QStest = this_QS, NPtest = this_NP$cv, Ftest = this_F, 
                spectrum = this_spectrum_peak, result = this_result))
}
