#' Residual QS diagnostic warning message.
#'
#' Generates text explaining why the QS diagnostic failed or generated a warning for regARIMA residuals.
#'
#' Version 3.3, 5/23/2023
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param test_full Logical scalar indicating whether to test the full series span.
#'        Default is \code{TRUE}.
#' @param test_span Logical scalar indicating whether to test the final 8-year span used by 
#'        the spectrum diagnostic. Default is \code{TRUE}.
#' @param p_limit_warn Numeric scalar; P-value limit for QS statistic for warning.
#'        Default is \code{0.05}.
#' @param return_both Logical scalar indicating whether the calling function will return both 
#'        the test results and why the test failed or produced a warning. Default is \code{FALSE}.
#' @return A text string denoting why the series generated a warning message for the QS of 
#'         regARIMA residuals.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                              x11="", transform.function = "log", forecast.maxlead=20,
#'                              check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_qs_rsd_warn <- 
#'    qs_rsd_warn_why(ukgas_udg, test_full = FALSE, p_limit_warn = 0.05, return_both = TRUE)
#' @export
qs_rsd_warn_why <- function(udg_list = NULL, test_full = TRUE, test_span = TRUE,  
    p_limit_warn = 0.05, return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 3.3, 5/23/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize \code{this_out_string}
    this_out_string <- ""
    
    # Test full span of series
    if (test_full) {
        # Check if the test fails, update \code{this_out_string} if necessary
        if (udg_list[["qsrsd"]][2] < p_limit_warn) {
            this_out_string <- "rsd"
            if (!return_both) {
                this_out_string <- paste("warn:", this_out_string, sep = " ")
            }
        }
    }
    
    # Test reduced (8-year) span of series
    if (test_span) {
        # Check if the test fails, update \code{this_out_string} if necessary
        if (udg_list[["qssrsd"]][2] < p_limit_warn) {
            if (nchar(this_out_string) > 0) {
                this_out_string <- paste(this_out_string, ";rsd.span", sep = "")
            } else {
                this_out_string <- "rsd.span"
                if (!return_both) {
                  this_out_string <- paste("warn:", this_out_string, sep = " ")
                }
            }
        }
    }
    
    # return results based on entry of \code{return_this}
    if (nchar(this_out_string) > 0) {
        return(this_out_string)
    } else {
        if (return_both) {
            return("    ")
        } else {
            return("pass")
        }
    }
    
}
