#' Warning or error messages for QS seasonal diagnostic
#'
#' Tests using the QS diagnostic developed by Maravall to determine if the original series is seasonal
#'
#' Version 4.2, 5/23/2023
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param test_full Logical scalar indicating whether to test the full series span
#'        Default is \code{TRUE}.
#' @param test_span Logical scalar indicating whether to test the final 8-year span used 
#'        by the spectrum diagnostic. Default is \code{TRUE}.
#' @param p_limit_pass Numeric scalar; P-value limit for QS statistic for passing.
#'        Default is \code{0.05}.
#' @param robust_sa Logical scalar indicating if original series adjusted for extremes is 
#'        included in testing. Default is \code{FALSE}.
#' @param return_both Logical scalar indicating whether the calling function will return both 
#'        the test results and why the test failed or produced a warning. Default is \code{FALSE}.
#' @return A text string denoting if the series had a worning message from the tests for 
#'         seasonality using the QS diagnostics. Can test the entire series or the last 8 years 
#'         or both. 
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- 
#'    seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)", 
#'                   x11="", transform.function = "log", forecast.maxlead=20,
#'                   check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_qs_warn_seasonal <- 
#'    qs_seasonal_warn_why(ukgas_udg, test_full = FALSE, p_limit_pass = 0.025, 
#'                         robust_sa=FALSE, return_both = TRUE)
#' @export
qs_seasonal_warn_why <- function(udg_list = NULL, test_full = TRUE, test_span = TRUE,  
    p_limit_pass = 0.05, robust_sa = TRUE, return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 4.2, 5/23/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize \code{this_out_string}
    this_out_string <- ""
    
    # Test full span of series
    if (test_full) {
        # initialize number of tests failed to 0
        n_test <- 0
        
        # get index of the QS statistic for the original series
        index_qs <- get_udg_index(udg_list, "qsori")
        
        # If this QS exists, check if the test fails, update \code{this_out_string} 
        # and \code{n_test} if necessary
        if (index_qs > 0) {
            if (udg_list[[index_qs]][2] > p_limit_pass) {
               if (return_both) {
                 this_out_string <- "ori"
               } else {
                 this_out_string <- "warn:ori"
               }
            }
            n_test <- n_test + 1
        }
        
        # check if testing original series with extreme values removed
        if (robust_sa) {
            # get index of the QS statistic for the original series with extreme values removed
            index_qs <- get_udg_index(udg_list, "qsorievadj")
            
            # If this QS exists, check if the test fails, update \code{this_out_string} 
            # and \code{n_test} if necessary
            if (index_qs > 0) {
                if (udg_list[[index_qs]][2] > p_limit_pass) {
                  if (nchar(this_out_string) > 0) {
                    this_out_string <- paste(this_out_string, ";orievadj", sep = "")
                  } else {
                    if (return_both) {
                      this_out_string <- "orievadj"
                    } else {
                      this_out_string <- "warn:orievadj"
                    }
                  }
                }
                n_test <- n_test + 1
            }
        }
        
        # If no QS statistics are found, return \code{'no_qs_stats'}
        if (n_test == 0) {
            return("no_qs_stats")
        }
    }
    
    # Test reduced (8-year) span of series
    if (test_span) {
        # initialize number of tests failed to 0
        n_test <- 0
        
        # get index of the QS statistic for the original series
        index_qs <- get_udg_index(udg_list, "qssori")
        
        # If this QS exists, check if the test fails, update \code{this_out_string} 
        # and \code{n_test} if necessary
        if (index_qs > 0) {
            if (udg_list[[index_qs]][2] > p_limit_pass) {
                if (nchar(this_out_string) > 0) {
                  this_out_string <- paste(this_out_string, ";ori.span", sep = "")
                } else {
                  if (return_both) {
                    this_out_string <- "ori.span"
                  } else {
                    this_out_string <- "warn:ori.span"
                  }
                }
            }
            n_test <- n_test + 1
        }
        
        # check if testing original series with extreme values removed
        if (robust_sa) {
            # get index of the QS statistic for the original series with extreme values removed
            index_qs <- get_udg_index(udg_list, "qsorievadj")
            
            # If this QS exists, check if the test fails, update \code{this_out_string} 
            # and \code{n_test} if necessary
            if (index_qs > 0) {
                if (udg_list[[index_qs]][2] > p_limit_pass) {
                  if (nchar(this_out_string) > 0) {
                    this_out_string <- paste(this_out_string, ";orievadj.span", sep = "")
                  } else {
                    if (return_both) {
                      this_out_string <- "orievadj.span"
                    } else {
                      this_out_string <- "warn:orievadj.span"
                    }
                  }
                }
                n_test <- n_test + 1
            }
        }
    }
    
    # If no QS statistics are found, return \code{'no_span_qs_stats'}
    if (n_test == 0) {
        return("no_span_qs_stats")
    }
    
    # return results based on entry of \code{return_this}
    if (nchar(this_out_string) > 0) {
        return(this_out_string)
    } else {
        if (return_both) {
            return("    ")
        } else {
            return("pass")
        }
    }
    
}
