#' Warning message for QS Test for residual seasonality
#'
#' Generates text explaining why the QS diagnostic generated a warning.
#'
#' Version 4.2, 5/24/2023
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param test_full Logical scalar indicating whether to test the full series span
#'        Default is \code{TRUE}.
#' @param test_span Logical scalar indicating whether to test the final 8-year span used by 
#'        the spectrum diagnostic. Default is \code{TRUE}.
#' @param p_limit_warn Numeric scalar; P-value limit for QS statistic for warning.
#'        Default is \code{0.05}.
#' @param robust_sa Logical scalar indicating if SA or irregular series adjusted for extremes is 
#'        included in testing. Default is \code{TRUE}.
#' @param return_both Logical scalar indicating whether the calling function will return both 
#         the test results and why the test failed or produced a warning. Default is \code{FALSE}.
#' @return  A text string denoting if the series passed or failed the tests of ARIMA diagnostics.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' ukgas_seas <- 
#'    seasonal::seas(UKgas, series.period = 4, arima.model = "(0 1 1)(0 1 1)",
#'                   x11="", transform.function = "log", forecast.maxlead=20,
#'                   check.print = c( "pacf", "pacfplot" ))
#' ukgas_udg <- seasonal::udg(ukgas_seas)
#' ukgas_qs_test <- qs_warn_why(ukgas_udg, test_full = FALSE, p_limit_warn = 0.025, return_both = TRUE)
#' @export
qs_warn_why <- function(udg_list = NULL, test_full = TRUE, test_span = TRUE, p_limit_warn = 0.05, 
    robust_sa = TRUE, return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 4.2, 5/24/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # Initialize \code{this_out_string}
    this_out_string <- ""
    
    # Test full span of series
    if (test_full) {
        # get index of the QS statistic for the seasonally adjusted data
        index_qs <- get_udg_index(udg_list, "qssadj")
        
        # If this QS exists, check if the test generates a warning message, 
        # update \code{this_out_string} if necessary
        if (index_qs > 0) {
            if (udg_list[["qssadj"]][2] < p_limit_warn) {
                this_out_string <- "sadj"
                if (!return_both) {
                  this_out_string <- paste("warn:", this_out_string, sep = " ")
                }
            }
        }
        
        # get index of the QS statistic for the irregular
        index_qs <- get_udg_index(udg_list, "qsirr")
        
        # If this QS exists, check if the test generates a warning message, 
        # update \code{this_out_string} if necessary
        if (index_qs > 0) {
            if (udg_list[["qsirr"]][2] < p_limit_warn) {
                if (nchar(this_out_string) > 0) {
                  this_out_string <- paste(this_out_string, ";irr", sep = "")
                } else {
                  this_out_string <- "irr"
                  if (!return_both) {
                    this_out_string <- paste("warn:", this_out_string, sep = " ")
                  }
                }
            }
        }
        
        
        # Test series adjusted for extremes
        if (robust_sa) {
            # get index of the QS statistic for the seasonally adjusted data adjusted for extreme values
            index_qs <- get_udg_index(udg_list, "qssadjevadj")
            
            # If this QS exists, check if the test fails, update \code{this_out_string} if necessary
            if (index_qs > 0) {
                if (udg_list[["qssadjevadj"]][2] < p_limit_warn) {
                  if (nchar(this_out_string) > 0) {
                    this_out_string <- paste(this_out_string, ";sadjevadj", sep = "")
                  } else {
                    this_out_string <- "sadjevadj"
                    if (!return_both) {
                      this_out_string <- paste("warn:", this_out_string, sep = " ")
                    }
                  }
                }
            }
            
            # get index of the QS statistic for the irregular adjusted for extreme values
            index_qs <- get_udg_index(udg_list, "qsirrevadj")
            
            # If this QS exists, check if the test fails, update \code{this_out_string} if necessary
            if (index_qs > 0) {
                if (udg_list[["qsirrevadj"]][2] < p_limit_warn) {
                  if (nchar(this_out_string) > 0) {
                    this_out_string <- paste(this_out_string, ";irrevadj", sep = "")
                  } else {
                    this_out_string <- "irrevadj"
                    if (!return_both) {
                      this_out_string <- paste("warn:", this_out_string, sep = " ")
                    }
                  }
                }
            }
        }
    }
    
    # Test reduced (8-year) span of series
    if (test_span) {
        # get index of the QS statistic for the seasonally adjusted data
        index_qs <- get_udg_index(udg_list, "qsssadj")
        
        # If this QS exists, check if the test fails, update \code{this_out_string} if necessary
        if (index_qs > 0) {
            if (udg_list[["qsssadj"]][2] < p_limit_warn) {
                if (nchar(this_out_string) > 0) {
                  this_out_string <- paste(this_out_string, ";sadj.span", sep = "")
                } else {
                  this_out_string <- "sadj.span"
                  if (!return_both) {
                    this_out_string <- paste("warn:", this_out_string, sep = " ")
                  }
                }
            }
        }
        
        # get index of the QS statistic for the seasonally adjusted data
        index_qs <- get_udg_index(udg_list, "qssirr")
        
        # If this QS exists, check if the test fails, update \code{this_out_string} if necessary
        if (index_qs > 0) {
            if (udg_list[["qssirr"]][2] < p_limit_warn) {
                if (nchar(this_out_string) > 0) {
                  this_out_string <- paste(this_out_string, ";irr.span", sep = "")
                } else {
                  this_out_string <- "irr.span"
                  if (!return_both) {
                    this_out_string <- paste("warn:", this_out_string, sep = " ")
                  }
                }
            }
        }
        
        # Test series adjusted for extremes
        if (robust_sa) {
            # get index of the QS statistic for the seasonally adjusted data adjusted for 
            # extreme values
            index_qs <- get_udg_index(udg_list, "qssadjevadj")
            
            # If this QS exists, check if the test fails, update \code{this_out_string} 
            # if necessary
            if (index_qs > 0) {
                if (udg_list[["qsssadjevadj"]][2] < p_limit_warn) {
                  if (nchar(this_out_string) > 0) {
                    this_out_string <- paste(this_out_string, ";sadjevadj.span", sep = "")
                  } else {
                    this_out_string <- "sadjevadj.span"
                    if (!return_both) {
                      this_out_string <- paste("warn:", this_out_string, sep = " ")
                    }
                  }
                }
            }
            
            # get index of the QS statistic for the irregular adjusted for extreme values
            index_qs <- get_udg_index(udg_list, "qssirrevadj")
            
            # If this QS exists, check if the test fails, update \code{this_out_string} 
            # if necessary
            if (index_qs > 0) {
                if (udg_list[["qssirrevadj"]][2] < p_limit_warn) {
                  if (nchar(this_out_string) > 0) {
                    this_out_string <- paste(this_out_string, ";irrevadj.span", sep = "")
                  } else {
                    this_out_string <- "irrevadj.span"
                    if (!return_both) {
                      this_out_string <- paste("warn:", this_out_string, sep = " ")
                    }
                  }
                }
            }
        }
    }
    
    # return results based on entry of \code{return_this}
    if (nchar(this_out_string) > 0) {
        return(this_out_string)
    } else {
        if (return_both) {
            return("    ")
        } else {
            return("pass")
        }
    }
    
}
