#' TERROR for R (applied to a list of series)
#'
#' Function that duplicates the functionality of the TERROR software (Caporello and Maravall 2004) 
#' that performs quality control on time series based on one step ahead forecasts 
#'
#' Version 3.5, 5/22/2023
#'
#' @param this_data_list List of time series (all series in list should be the same frequency and 
#'        have the same ending date.)
#' @param this_lead Number of forecasts generated by the seas run. Default is 36.
#' @param this_log logical scalar, if TRUE \code{transform.function} will be set to \code{log} 
#'        in the call to the \code{seas} function, otherwise \code{auto} will be used. 
#'        Default is \code{TRUE}.
#' @param this_aictest a character string with the entries for the \code{regression.aictest}  
#'        argument to the \code{seas} function from the \code{seasonal} package. 
#'        Default is \code{NULL}.
#' @param this_terror_lags Integer scalar for number of forecast lags from the end of series  
#'        where t-statistics are collected. Must be either 1, 2, or 3.
#' @return list of t-statistics generated by out of sample forecast error for the last 1 to 3 
#'         observation of each series in the list.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples 
#' emp_terror <- r_terror_list(employment_list, this_log = FALSE,
#'                             this_lead = 60, this_terror_lags = 3) 
#' @import stats
#' @export
r_terror_list <- function(this_data_list = NULL, this_lead = 36, 
                          this_log = TRUE, this_aictest = NULL, 
                          this_terror_lags = 1) {
    # Author: Brian C. Monsell (OEUS) Version 3.5, 5/22/2023
    
    # check if a value is specified for \code{this_data_list}
    if (is.null(this_data_list)) {
        stop("must specify a list of time series")
    } else {
        if (!is.list(this_data_list)) {
            stop("must specify a list")
        }
    }
    
    # get element names, number of elements for \code{this_data_list}
    list_names <- names(this_data_list)
    num_names <- length(list_names)
    
    # get ending dates for all series in the list
    end_list <- lapply(this_data_list, function(x) try(end(x)))
    
    # check if ending dates are the same for all series in the list
    end_date <- end_list[[1]]
    lDate <- lapply(end_list, function(x) try(compare_dates(x, comp_date = end_date)))
    if (sum(unlist(lDate)) < num_names) {
        stop("Series in list have different ending dates.")
    }
    
    # run seasonal on list with automatic modeling
    this_terror_list <- 
        lapply(this_data_list, function(x) try(r_terror(x, max_lead = this_lead, 
               log_transform = this_log, aictest = this_aictest, 
               terror_lags = this_terror_lags)))
    
    # return UDG value of \code{'forctval01'}
    return(this_terror_list)
    
}
