#' Warning message for spectral peaks
#'
#' Generate warning message related to spectral peaks for a given X-13ARIMA-SEATS spectrum.
#'
#' Version 3.2, 5/24/2023
#'
#' @param udg_list List object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param peak_warn_level Integer scalar - limit to produce a warning that a frequency may 
#'        have a spectral peak. Default is 3.
#' @param this_spec text string with the spectrum being tested. Allowable entries are 
#'        \code{'spcori'}, \code{'spcsa'}, \code{'spcirr'}, \code{'spcrsd'}. 
#'        Default is \code{'spcori'}.
#' @param return_both Logical scalar indicating whether the calling function will return both 
#' the test results and why the test failed or produced a warning. Default is \code{FALSE}.
#' @return A text string denoting if the series passed the tests of spectrum diagnostics, 
#'         or why the series did not pass. Note that for spcori, the series fails if none of 
#'         the frequencies tested had peaks 
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' air_seas <- 
#'    seasonal::seas(AirPassengers, transform.function = "log",  
#'                   arima.model = "(0 1 1)(0 1 1)", x11 = "")
#' air_seas_udg <- seasonal::udg(air_seas)
#' this_spec_peak_warn_why <- 
#'     spec_peak_warn_why(air_seas_udg, this_spec = 'spcori', return_both = TRUE)
#' @export
spec_peak_warn_why <- function(udg_list = NULL, peak_warn_level = 3, this_spec = "spcsa", 
                               return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 3.2, 5/24/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # check to see if a spectrum was estimated in this run.  if not, return \code{'none'}
    if (udg_list[["spectrum"]] == "no") {
        return("none")
    }
    # check to see if the value of spec is valid.  if not, print error message
    this_spec <- tolower(this_spec)
    good_spec <- c("spcori", "spcsa", "spcirr", "spcrsd")
    is_arg <- grep(this_spec, good_spec)
    if (length(is_arg) == 0) {
        stop(paste("Value of thisStat '", this_spec, "' not allowed.", sep = ""))
    }
    # set number of peaks to zero
    n_peaks <- 0
    # check to see if one of the seasonal frequencies has a peak > \code{peak_warn_level}  
    # if so, update number of 'warning' peaks
    if (this_spec == "spcsa" | this_spec == "spcirr" | this_spec == "spcrsd") {
        for (i in 1:5) {
            this_key <- paste(this_spec, ".s", i, sep = "")
            this_peak <- udg_list[[this_key]]
            this_len <- length(this_peak)
            if (this_len > 1) {
                if (as.numeric(this_peak[1]) > peak_warn_level) {
                  n_peaks <- n_peaks + 1
                  if (n_peaks == 1) {
                    this_out_string <- paste(this_spec, ".s", i, sep = "")
                    if (!return_both) {
                      this_out_string <- paste("warn: ", this_out_string, sep = "")
                    }
                  } else {
                    this_out_string <- paste(this_out_string, "; ", this_spec, ".s", i, sep = "")
                  }
                }
            } else {
                if (this_peak != "nopeak") {
                  if (as.numeric(this_peak) > peak_warn_level) {
                    n_peaks <- n_peaks + 1
                    if (n_peaks == 1) {
                      this_out_string <- paste(this_spec, ".s", i, sep = "")
                      if (!return_both) {
                        this_out_string <- paste("warn: ", this_out_string, sep = "")
                      }
                    } else {
                      this_out_string <- paste(this_out_string, "; ", this_spec, ".s", i, sep = "")
                    }
                  }
                }
            }
        }
    }
    # check to see if the second trading day frequency has a peak > \code{peak_warn_level}.  
    # if so, update number of 'warning' peaks
    this_key <- paste(this_spec, ".t2", sep = "")
    this_peak <- udg_list[[this_key]]
    this_len <- length(this_peak)
    if (this_len > 1) {
        if (as.numeric(this_peak[1]) > peak_warn_level) {
            n_peaks <- n_peaks + 1
            if (n_peaks == 1) {
                this_out_string <- paste(this_spec, ".t2", sep = "")
                if (!return_both) {
                  this_out_string <- paste("warn: ", this_out_string, sep = "")
                }
            } else {
                this_out_string <- paste(this_out_string, "; ", this_spec, ".t2", sep = "")
            }
        }
    }
    # if the number of 'warning' peaks found is > 0, return \code{this_out_string}.
    if (n_peaks > 0) {
        return(this_out_string)
    }
    
    # else return \code{'pass'} or blanks
    if (return_both) {
        return("    ")
    } else {
        return("pass")
    }
    
}

