#' Failure text for spectral peaks
#'
#' generate text on why spectral peaks are flagged
#'
#' Version 3.1, 5/24/2023
#'
#' @param udg_list - list object generated by \code{udg()} function of the \code{seasonal} package.
#'        This is a required entry.
#' @param peak_level Integer scalar - limit to determine if a frequency has a spectral peak.
#' @param this_spec text string with the spectrum being tested allowable entries are 
#'        \code{'spcori'}, \code{'spcsa'}, \code{'spcirr'}, \code{'spcrsd'}.
#'        Default is \code{'spcori'}.
#' @param return_both Logical scalar indicating whether the calling function will return both 
#'        the test results and why the test failed or produced a warning. Default is \code{FALSE}.
#' @return A text string denoting if the series passed the tests of spectrum diagnostics, 
#'         or why the series did not pass. Note that for \code{'spcori'}, the series fails 
#          if none of the frequencies tested had peaks. 
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples
#' air_seas <- seasonal::seas(AirPassengers, transform.function = "log",  
#'                         arima.model = "(0 1 1)(0 1 1)", x11 = "")
#' air_seas_udg <- seasonal::udg(air_seas)
#' this_spec_peak_fail_why <- 
#'     spec_peak_fail_why(air_seas_udg, this_spec = 'spcori', return_both = TRUE)
#' @export
spec_peak_fail_why <- function(udg_list = NULL, peak_level = 6, this_spec = "spcsa", 
                               return_both = FALSE) {
    # Author: Brian C. Monsell (OEUS) Version 3.1, 5/24/2023
    
    # check if a value is specified for \code{udg_list}
    if (is.null(udg_list)) {
        stop("must specify a list of UDG diagnostics")
    } else {
        if (!is.list(udg_list)) {
            stop("must specify a list")
        }
    }
    
    # check to see if a spectrum was estimated in this run.  if not, return \code{'none'}
    if (udg_list[["spectrum"]] == "no") {
        return("none")
    }
    # check to see if the value of spec is valid.  if not, print error message
    this_spec <- tolower(this_spec)
    good_spec <- c("spcori", "spcsa", "spcirr", "spcrsd")
    is_arg <- grep(this_spec, good_spec)
    if (length(is_arg) == 0) {
        stop(paste("Value of thisStat '", this_spec, "' not allowed.", sep = ""))
    }
    # initialize number of peaks to zero
    n_peaks <- 0
    this_out_string <- ""
    # check to see if one of the seasonal frequencies has a peak > peak_level.  if so, 
    # update number of peaks
    for (i in 1:5) {
        this_key <- paste(this_spec, ".s", i, sep = "")
        this_peak <- udg_list[[this_key]]
        this_len <- length(this_peak)
        if (this_len > 1) {
            if (as.numeric(this_peak[1]) > peak_level) {
                n_peaks <- n_peaks + 1
                if (n_peaks == 1) {
                  this_out_string <- paste(this_spec, ".s", i, sep = "")
                  if (!return_both) {
                    this_out_string <- paste("fail: ", this_out_string, sep = "")
                  }
                } else {
                  this_out_string <- paste(this_out_string, "; ", this_spec, ".s", i, sep = "")
                }
            }
        }
    }
    
    if (this_spec == "spcori") {
        nsP <- n_peaks
    }
    
    # check to see if the first trading day frequency has a peak > peak_level.  if so, 
    # update number of peaks
    this_key <- paste(this_spec, ".t1", sep = "")
    this_peak <- udg_list[[this_key]]
    this_len <- length(this_peak)
    if (this_len > 1) {
        if (as.numeric(this_peak[1]) > peak_level) {
            n_peaks <- n_peaks + 1
            if (n_peaks == 1) {
                this_out_string <- paste(this_spec, ".t1", sep = "")
                if (!return_both) {
                  this_out_string <- paste("fail: ", this_out_string, sep = "")
                }
            } else {
                this_out_string <- paste(this_out_string, "; ", this_spec, ".t1", sep = "")
            }
        }
    }
    # if the number of peaks found is > 0, return \code{this_out_string}
    if (this_spec == "spcori") {
        if (nsP < 1) {
            if (return_both) {
                return("no peaks")
            } else {
                return("fail: no peaks")
            }
        }
        if (n_peaks > nsP) {
            if (nsP < 1) {
                if (return_both) {
                  return("TD peak")
                } else {
                  return("fail: TD peak")
                }
            }
        }
    } else {
        if (n_peaks > 0) {
            return(this_out_string)
        }
    }
    
    # else return \code{'pass'} or blanks
    if (return_both) {
        return("    ")
    } else {
        return("pass")
    }
    
}

