#' Process a list of \code{seas} elements 
#' 
#' Process a list of \code{seas} elements to find the elements that are greater than or 
#' less than a particular limit for a diagnostic.
#' 
#' Version 3.3, 5/24/2023
#'
#' @param seas_obj_list - list of \code{seas} objects generated by the \code{seasonal} package.
#'        This is a required entry.
#' @param this_key - character string containing keyword of the \code{udg} function 
#'        that returns a numeric value. Default is \code{'autoout'}.
#' @param this_limit - numeric object which serves as the limit of the diagnostic 
#'        referred to in \code{this_key}. Default is \code{'5'}
#' @param this_abs Logical scalar that indicates whether the absolute value is taken 
#'        of the numbers before the comparison is made. (default is \code{FALSE})
#' @param greater_than - logical object that specified whether the element names returned are 
#'        greater than or less than the limit specified in \code{this_limit}.
#'        Default is \code{TRUE}.
#' @return A vector of list element names where this_key is greater than or less than the limit 
#'         specified in \code{this_limit}. If nothing matches, the function will output the 
#'         string \code{'none'}.
#'
#' @author Brian C. Monsell, \email{monsell.brian@@bls.gov} or \email{bcmonsell@@gmail.com}
#'
#' @examples 
#' emp_seas_list <- seasonal::seas(employment_data_mts, 
#'                       slidingspans = "", transform.function = "log", 
#'                       x11 = "", arima.model = "(0 1 1)(0 1 1)",
#'                       forecast.maxlead=36, check.print = c( "pacf", "pacfplot" ))
#' emp_seas_update <- 
#'    Filter(function(x) inherits(x, "seas"), emp_seas_list)
#' xt_bad_m7 <- 
#'    udg_series(emp_seas_update, this_key = 'f3.m07', this_limit = 1.2)
#' xt_bad_q2 <- 
#'    udg_series(emp_seas_update, this_key = 'f3.qm2', this_limit = 1.2)
#' @export
udg_series <- function(seas_obj_list = NULL, this_key = "autoout", this_limit = 5, 
                       this_abs = FALSE, greater_than = TRUE) {
    # Author: Brian C. Monsell (OEUS) Version 3.3, 5/24/2023
    
    # check if a value is specified for \code{this_seas_list}
    if (is.null(seas_obj_list)) {
        stop("must specify a list of seas objects")
    } else {
        if (!is.list(seas_obj_list)) {
            stop("must specify a list")
        }
    }
    
    # filter elements of the list that are not \code{seas} objects
    seas_obj_list_update <-
      Filter(function(x) inherits(x, "seas"), seas_obj_list)

    # extract diagnostic \code{this_key} from \code{seas_obj_list_update}
    udg_list <- lapply(seas_obj_list_update, function(x) try(seasonal::udg(x, this_key)))
    
    # check \code{udg_error} for try errors if try errors found, print out error messages and 
    # set \code{udg_error} to NULL
    udg_error <- which_error(udg_list)
    if (length(udg_error > 1)) {
        udg_list[[udg_error]] <- NULL
        print(paste("try errors found - ", udg_error))
    }
    
    # if there are no entries in \code{udg_error}, print error message and return NULL
    if (length(udg_list) == 0) {
        print("No series to process.")
        return(NULL)
    }
    
    # if \code{this_abs} is true, return the element names on the list that are either 
    # greater than or less thanin absolute value than \code{this_limit}
    if (this_abs) {
        if (greater_than) {
            udg_names <- names(udg_list)[as.vector(abs(unlist(udg_list)) > this_limit)]
        } else {
            udg_names <- names(udg_list)[as.vector(abs(unlist(udg_list)) < this_limit)]
        }
    } else {
        # else, return the element names on the list that are either greater than or 
        #       less than \code{this_limit}
        if (greater_than) {
            udg_names <- names(udg_list)[as.vector(unlist(udg_list) > this_limit)]
        } else {
            udg_names <- names(udg_list)[as.vector(unlist(udg_list) < this_limit)]
        }
    }
    
    # return either the names or \code{'none'} if there are no names
    if (length(udg_names) > 0) {
        return(udg_names)
    } else {
        return("none")
    }
}
